# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=500, upload_to='')),
                ('about', models.CharField(blank=True, max_length=1000)),
                ('comission_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('activated', models.BooleanField()),
                ('activation_key', models.CharField(max_length=40)),
                ('key_expiration', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
