# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161014_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
