# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161014_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
