# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_payment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img/avatars'),
        ),
    ]
