# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='photo',
            field=models.ImageField(upload_to='img/categorias/'),
        ),
    ]
