# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161005_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='static/img/categorias/cube.png', upload_to='img/produtos/'),
            preserve_default=False,
        ),
    ]
