# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='file',
            new_name='uploaded_file',
        ),
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfile',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
