# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20161005_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
