# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20161005_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='name',
            field=models.CharField(default='Arquivo 1', max_length=100),
            preserve_default=False,
        ),
    ]
