# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20161017_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
