# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20161019_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller_commission',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
            preserve_default=False,
        ),
    ]
