# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
